--dofile("mods/dlc2/effects/impact_paveway.lua")
dofile(path .. "/effects/util.lua")
dofile("effects/device_explode_util.lua")
--  age (in seconds) at which the explosion actor deletes itself
--  make sure this exceedes the age of all effects
LifeSpan = 12

SoundEvent = "mods/weapon_pack/effects/flak_explode.lua"

Effects =
{
	{
		Type = "sprite",
		TimeToTrigger = 0,
		LocalPosition = { x = 0, y = 0, z = 50 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = "effects/media/CloudLarge",
		Additive = true,
		TimeToLive = 1.5,
		InitialSize = 1.5,
		ExpansionRate = 250,
		AngularVelocity = 0,
		AngleMaxDeviation = 180,
		RandomAngularVelocityMagnitude = 2,
		Colour1 = { 255, 255, 255, 255 },
		Colour2 = { 255, 255, 255, 0 },
	},
	{
	--SPARKS
		Type = "sparks",
		TimeToTrigger = 0,
		SparkCount = 8,
		LocalPosition = { x = 0, y = 0, z = -0.5 },	-- how to place the origin relative to effect position and direction (0, 0) 
		Texture = "effects/media/flame",

		Gravity = 250,						-- gravity applied to particle (981 is earth equivalent)
		
		EvenDistribution =					-- distribute sparks evenly between two angles with optional variation
		{
			Min = -180,						-- minimum angle in degrees (e.g. -180, 45, 0)
			Max = 180,						-- maximum angle in degrees (e.g. -180, 45, 0)
			StdDev = 5,						-- standard deviation at each iteration in degrees (zero will make them space perfectly even)
		},

		Keyframes =							
		{
			{
				Angle = -180,
				RadialOffsetMin = 0,
				RadialOffsetMax = 20,
				ScaleMean = 0.4,
				ScaleStdDev = 0.05,
				SpeedStretch = 0,
				SpeedMean = 1000,
				SpeedStdDev = 200,
				Drag = 3,
				RotationMean = 45,
				RotationStdDev = 10,
				RotationalSpeedMean = 10,
				RotationalSpeedStdDev = 5,
				AgeMean = 0.25,
				AgeStdDev = 0.05,
				AlphaKeys = { 0.1, 0.5 },
				ScaleKeys = { 0.1, 0.5 },
			},
			{
				Angle = 180,
				RadialOffsetMin = 0,
				RadialOffsetMax = 20,
				ScaleMean = 0.4,
				ScaleStdDev = 0.05,
				SpeedStretch = 0,
				SpeedMean = 1000,
				SpeedStdDev = 200,
				Drag = 3,
				RotationMean = -45,
				RotationStdDev = -10,
				RotationalSpeedMean = 10,
				RotationalSpeedStdDev = 5,
				AgeMean = 0.25,
				AgeStdDev = 0.05,
				AlphaKeys = { 0.1, 0.5 },
				ScaleKeys = { 0.1, 0.5 },
			},
		},
	},
	{
	--DEBRIS
		Type = "sparks",
		TimeToTrigger = 0.05,
		SparkCount = 8,
		LocalPosition = { x = 0, y = 0, z = -0.25 },	-- how to place the origin relative to effect position and direction (0, 0) 
		Texture = "effects/media/debris",

		Gravity = 250,						-- gravity applied to particle (981 is earth equivalent)
		
		EvenDistribution =					-- distribute sparks evenly between two angles with optional variation
		{
			Min = -180,						-- minimum angle in degrees (e.g. -180, 45, 0)
			Max = 180,						-- maximum angle in degrees (e.g. -180, 45, 0)
			StdDev = 5,						-- standard deviation at each iteration in degrees (zero will make them space perfectly even)
		},

		Keyframes =							
		{
			{
				Angle = -180,
				RadialOffsetMin = 0,
				RadialOffsetMax = 20,
				ScaleMean = 0.5,
				ScaleStdDev = 0.1,
				SpeedStretch = 0.2,
				SpeedMean = 1000,
				SpeedStdDev = 200,
				Drag = 3,
				RotationMean = 45,
				RotationStdDev = 10,
				RotationalSpeedMean = 10,
				RotationalSpeedStdDev = 5,
				AgeMean = 0.25,
				AgeStdDev = 0.05,
				AlphaKeys = { 0.1, 0.5 },
				ScaleKeys = { 0.1, 0.5 },
			},
			{
				Angle = 180,
				RadialOffsetMin = 0,
				RadialOffsetMax = 20,
				ScaleMean = 0.4,
				ScaleStdDev = 0.05,
				SpeedStretch = 0,
				SpeedMean = 1000,
				SpeedStdDev = 200,
				Drag = 3,
				RotationMean = -45,
				RotationStdDev = -10,
				RotationalSpeedMean = 10,
				RotationalSpeedStdDev = 5,
				AgeMean = 0.25,
				AgeStdDev = 0.05,
				AlphaKeys = { 0.1, 0.5 },
				ScaleKeys = { 0.1, 0.5 },
			},
		},
	},
	{
		Type = "sprite",
		TimeToTrigger = 0,
		LocalPosition = { x = 0, y = 0, z = 0 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = "effects/media/AdditiveLarge",
		Additive = true,
		TimeToLive = 0.2,
		InitialSize = 2,
		ExpansionRate = 150,
		AngularVelocity = 0,
		AngleMaxDeviation = 180,
		RandomAngularVelocityMagnitude = 6,
		Colour1 = { 251, 187, 62, 255 },
		Colour2 = { 241, 167, 24, 0 },
	},
	{
		Type = "sprite",
		TimeToTrigger = 0,
		LocalPosition = { x = 0, y = 0, z = -100 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = path .. "/effects/media/bloom1.png",
		Additive = true,
		TimeToLive = 0.16,
		InitialSize = 6.0,
		ExpansionRate = 100,
		Angle = -90,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 200,
		Colour1 = { 255, 255, 255, 190 },
		Colour2 = { 255, 190, 50, 60 },
	},


	{
		Type = "sprite",
		TimeToTrigger = 0,
		LocalPosition = { x = 0, y = 0, z = 50 },
		LocalVelocity = { x = 0, y = 30, z = 0 },
		Acceleration = { x = 0, y = -10, z = 0 },
		Drag = 0,
		Sprite = "effects/media/CloudLarge",
		Additive = false,
		TimeToLive = 3,
		InitialSize = 2,
		ExpansionRate = 250,
		AngularVelocity = 0,
		AngleMaxDeviation = 180,
		RandomAngularVelocityMagnitude = 2,
		Colour1 = { 255, 255, 255, 255 },
		Colour2 = { 255, 255, 255, 0 },
	},
   {
		Type = "sprite",
		TimeToTrigger = 0,
		LocalPosition = { x = 0, y = 50, z = 50 },
		LocalVelocity = { x = 0, y = 100, z = 0 },
		Acceleration = { x = 0, y = -10, z = 0 },
		Drag = 0,
      Gravity = 700,
		Sprite = "effects/media/CloudLarge",
		Additive = false,
		TimeToLive = 2.5,
		InitialSize = 2,
		ExpansionRate = 40,
		AngularVelocity = 0,
		AngleMaxDeviation = 40,
		RandomAngularVelocityMagnitude = 0.5,
		Colour1 = { 255, 255, 255, 255 },
		Colour2 = { 255, 255, 255, 0 },
	},
   {
		Type = "sprite",
		TimeToTrigger = 0,
		LocalPosition = { x = 0, y = 80, z = 50 },
		LocalVelocity = { x = 0, y = 200, z = 0 },
		Acceleration = { x = 0, y = -10, z = 0 },
		Drag = 0,
      Gravity = 800,
		Sprite = "effects/media/CloudLarge",
		Additive = false,
		TimeToLive = 2.5,
		InitialSize = 1.5,
		ExpansionRate = 20,
		AngularVelocity = 0,
		AngleMaxDeviation = 30,
		RandomAngularVelocityMagnitude = 1,
		Colour1 = { 235, 235, 235, 255 },
		Colour2 = { 255, 255, 255, 0 },
	},
   {
		Type = "sprite",
		TimeToTrigger = 0.8,
		LocalPosition = { x = 0, y = 80, z = 50 },
		LocalVelocity = { x = 0, y = 220, z = 0 },
		Acceleration = { x = 0, y = -10, z = 0 },
		Drag = 0,
      Gravity = 900,
		Sprite = "effects/media/CloudLarge",
		Additive = false,
		TimeToLive = 2.5,
		InitialSize = 1.5,
		ExpansionRate = 20,
		AngularVelocity = 0,
		AngleMaxDeviation = 30,
		RandomAngularVelocityMagnitude = 1,
		Colour1 = { 235, 235, 235, 255 },
		Colour2 = { 255, 255, 255, 0 },
	},
   {
		Type = "sprite",
		TimeToTrigger = 0,
		LocalPosition = { x = 0, y = 100, z = 50 },
		LocalVelocity = { x = 0, y = 250, z = 0 },
		Acceleration = { x = 0, y = -10, z = 0 },
		Drag = 0,
      Gravity = 1000,
		Sprite = "effects/media/CloudLarge",
		Additive = false,
		TimeToLive = 2,
		InitialSize = 1,
		ExpansionRate = 20,
		AngularVelocity = 0,
		AngleMaxDeviation = 30,
		RandomAngularVelocityMagnitude = 1,
		Colour1 = { 200, 200, 200, 255 },
		Colour2 = { 255, 255, 255, 0 },
	},
   Flames(2, 0.4, 1400),
   Flames(4, 0.05, 1800),
   Dirt(0.2, 2000),
   Smoke(11, 10, 5, 200),
	{
		Type = "sprite",
		TimeToTrigger = 0.12,
		LocalPosition = { x = 0, y = 0, z = -100 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = path .. "/effects/media/bloom3.png",
		Additive = true,
		TimeToLive = 0.2,
		InitialSize = 15,
		ExpansionRate = -700,
		Angle = -90,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 100,
		Colour1 = { 255, 222, 100, 50 },
		Colour2 = { 255, 170, 0, 20 },
	},
   {
		Type = "sprite",
		TimeToTrigger = 0.12,
		LocalPosition = { x = 300, y = 0, z = -100 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = path .. "/effects/media/bloom3.png",
		Additive = true,
		TimeToLive = 0.2,
		InitialSize = 15,
		ExpansionRate = -700,
		Angle = -90,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 100,
		Colour1 = { 255, 222, 100, 50 },
		Colour2 = { 255, 170, 0, 20 },
	},
   {
		Type = "sprite",
		TimeToTrigger = 0,
		LocalPosition = { x = 0, y = 40, z = 0 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = "missile_explosion",
		Additive = false,
		TimeToLive = 1,
		InitialSize = 2,
		ExpansionRate = 0.5,
		Angle = -90,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 0,
		Colour1 = { 255, 255, 255, 255 },
		Colour2 = { 200, 200, 200, 200 },
	},
   {
		Type = "sprite",
		TimeToTrigger = 26,
		LocalPosition = { x = -120, y = -200, z = -100 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = path .. "/effects/media/bloom1.png",
		Additive = true,
		TimeToLive = 0.08,
		InitialSize = 6,
		ExpansionRate = -20,
		Angle = 0,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 700,
		Colour1 = { 255, 140, 255, 255 },
		Colour2 = { 255, 140, 255, 128 },
	},

}
--[[
Effects =
{	
	{
		Type = "sprite",
		TimeToTrigger = 0,
		LocalPosition = { x = 0, y = 0, z = 50 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = "effects/media/CloudLarge",
		Additive = false,
		TimeToLive = 1.5,
		InitialSize = 1.5,
		ExpansionRate = 250,
		AngularVelocity = 0,
		AngleMaxDeviation = 180,
		RandomAngularVelocityMagnitude = 2,
		Colour1 = { 255, 255, 255, 255 },
		Colour2 = { 255, 255, 255, 0 },
	},
	{
	--SPARKS
		Type = "sparks",
		TimeToTrigger = 0,
		SparkCount = 8,
		LocalPosition = { x = 0, y = 0, z = -0.5 },	-- how to place the origin relative to effect position and direction (0, 0) 
		Texture = path .. "/effects/media/flame",

		Gravity = 250,						-- gravity applied to particle (981 is earth equivalent)
		
		EvenDistribution =					-- distribute sparks evenly between two angles with optional variation
		{
			Min = -180,						-- minimum angle in degrees (e.g. -180, 45, 0)
			Max = 180,						-- maximum angle in degrees (e.g. -180, 45, 0)
			StdDev = 5,						-- standard deviation at each iteration in degrees (zero will make them space perfectly even)
		},

		Keyframes =							
		{
			{
				Angle = -180,
				RadialOffsetMin = 0,
				RadialOffsetMax = 20,
				ScaleMean = 0.4,
				ScaleStdDev = 0.05,
				SpeedStretch = 0,
				SpeedMean = 1000,
				SpeedStdDev = 200,
				Drag = 3,
				RotationMean = 45,
				RotationStdDev = 10,
				RotationalSpeedMean = 10,
				RotationalSpeedStdDev = 5,
				AgeMean = 0.25,
				AgeStdDev = 0.05,
				AlphaKeys = { 0.1, 0.5 },
				ScaleKeys = { 0.1, 0.5 },
			},
			{
				Angle = 180,
				RadialOffsetMin = 0,
				RadialOffsetMax = 20,
				ScaleMean = 0.4,
				ScaleStdDev = 0.05,
				SpeedStretch = 0,
				SpeedMean = 1000,
				SpeedStdDev = 200,
				Drag = 3,
				RotationMean = -45,
				RotationStdDev = -10,
				RotationalSpeedMean = 10,
				RotationalSpeedStdDev = 5,
				AgeMean = 0.25,
				AgeStdDev = 0.05,
				AlphaKeys = { 0.1, 0.5 },
				ScaleKeys = { 0.1, 0.5 },
			},
		},
	},
	{
	--DEBRIS
		Type = "sparks",
		TimeToTrigger = 0.05,
		SparkCount = 8,
		LocalPosition = { x = 0, y = 0, z = -0.25 },	-- how to place the origin relative to effect position and direction (0, 0) 
		Texture = path .. "/effects/media/debris",

		Gravity = 250,						-- gravity applied to particle (981 is earth equivalent)
		
		EvenDistribution =					-- distribute sparks evenly between two angles with optional variation
		{
			Min = -180,						-- minimum angle in degrees (e.g. -180, 45, 0)
			Max = 180,						-- maximum angle in degrees (e.g. -180, 45, 0)
			StdDev = 5,						-- standard deviation at each iteration in degrees (zero will make them space perfectly even)
		},

		Keyframes =							
		{
			{
				Angle = -180,
				RadialOffsetMin = 0,
				RadialOffsetMax = 20,
				ScaleMean = 0.5,
				ScaleStdDev = 0.1,
				SpeedStretch = 0.2,
				SpeedMean = 1000,
				SpeedStdDev = 200,
				Drag = 3,
				RotationMean = 45,
				RotationStdDev = 10,
				RotationalSpeedMean = 10,
				RotationalSpeedStdDev = 5,
				AgeMean = 0.25,
				AgeStdDev = 0.05,
				AlphaKeys = { 0.1, 0.5 },
				ScaleKeys = { 0.1, 0.5 },
			},
			{
				Angle = 180,
				RadialOffsetMin = 0,
				RadialOffsetMax = 20,
				ScaleMean = 0.4,
				ScaleStdDev = 0.05,
				SpeedStretch = 0,
				SpeedMean = 1000,
				SpeedStdDev = 200,
				Drag = 3,
				RotationMean = -45,
				RotationStdDev = -10,
				RotationalSpeedMean = 10,
				RotationalSpeedStdDev = 5,
				AgeMean = 0.25,
				AgeStdDev = 0.05,
				AlphaKeys = { 0.1, 0.5 },
				ScaleKeys = { 0.1, 0.5 },
			},
		},
	},
	{
		Type = "sprite",
		TimeToTrigger = 0,
		LocalPosition = { x = 0, y = 0, z = 0 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = path .. "/effects/media/AdditiveLarge",
		Additive = true,
		TimeToLive = 0.2,
		InitialSize = 2,
		ExpansionRate = 150,
		AngularVelocity = 0,
		AngleMaxDeviation = 180,
		RandomAngularVelocityMagnitude = 6,
		Colour1 = { 251, 187, 62, 255 },
		Colour2 = { 241, 167, 24, 0 },
	},

}
]]