dofile("mods/dlc2/effects/impact_paveway.lua")
dofile(path .. "/effects/util.lua")
dofile("effects/device_explode_util.lua")
Sprites = {}
LifeSpan = 15
SoundEvent = "mods/dogfights/effects/HUGE_EXPLOSION"

table.insert(Effects, Flames(6, 0.4, 1400))
table.insert(Effects,
	{
		Type = "shake",
		PlayForEnemy = true,
		FalloffStart = 1000,
		FalloffEnd = 6000,
		TimeToTrigger = 0,
		TimeToLive = 0.35,
		Magnitude = 100,
	})
table.insert(Effects,
	{
		Type = "sprite",
		TimeToTrigger = 0.12,
		LocalPosition = { x = 0, y = 0, z = -100 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = path .. "/effects/media/bloom3.png",
		Additive = true,
		TimeToLive = 0.4,
		InitialSize = 15,
		ExpansionRate = -700,
		Angle = -90,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 100,
		Colour1 = { 255, 222, 100, 188 },
		Colour2 = { 255, 170, 0, 30 },
	})
	table.insert(Effects,
	{
		Type = "sprite",
		TimeToTrigger = 0.12,
		LocalPosition = { x = 300, y = 0, z = -100 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = path .. "/effects/media/bloom3.png",
		Additive = true,
		TimeToLive = 0.4,
		InitialSize = 15,
		ExpansionRate = -700,
		Angle = -90,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 100,
		Colour1 = { 255, 222, 100, 188 },
		Colour2 = { 255, 170, 0, 30 },
	})
	table.insert(Effects,
	{
		Type = "sprite",
		TimeToTrigger = 0.2,
		LocalPosition = { x = -300, y = 100, z = -100 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = path .. "/effects/media/bloom3.png",
		Additive = true,
		TimeToLive = 0.4,
		InitialSize = 15,
		ExpansionRate = -700,
		Angle = -90,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 100,
		Colour1 = { 255, 222, 100, 188 },
		Colour2 = { 255, 170, 0, 30 },
	})
table.insert(Effects,
	{
		Type = "sprite",
		TimeToTrigger = 0.12,
		LocalPosition = { x = 0, y = 0, z = -100 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = path .. "/effects/media/bloom1.png",
		Additive = true,
		TimeToLive = 0.32,
		InitialSize = 23,
		ExpansionRate = -900,
		Angle = -90,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 700,
		Colour1 = { 255, 170, 120, 190 },
		Colour2 = { 255, 100, 20, 30 },
	})
table.insert(Effects,
	{
		Type = "sprite",
		TimeToTrigger = 0,
		LocalPosition = { x = 0, y = 0, z = -100 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = path .. "/effects/media/bloom1.png",
		Additive = true,
		TimeToLive = 0.08,
		InitialSize = 6,
		ExpansionRate = -20,
		Angle = 0,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 700,
		Colour1 = { 255, 140, 255, 255 },
		Colour2 = { 255, 140, 255, 128 },
	})
table.insert(Effects,
	{
		Type = "sprite",
		TimeToTrigger = 0.12,
		LocalPosition = { x = 0, y = 0, z = -100 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = path .. "/effects/media/bloom1.png",
		Additive = true,
		TimeToLive = 0.08,
		InitialSize = 6,
		ExpansionRate = -20,
		Angle = 0,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 700,
		Colour1 = { 255, 170, 255, 255 },
		Colour2 = { 255, 170, 255, 255 },
	})
table.insert(Effects,
	{
		Type = "sprite",
		TimeToTrigger = 0,
		LocalPosition = { x = 0, y = 180, z = 0 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = "missile_explosion",
		Additive = false,
		TimeToLive = 1,
		InitialSize = 4,
		ExpansionRate = 0.5,
		Angle = -90,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 0,
		Colour1 = { 255, 255, 255, 255 },
		Colour2 = { 255, 255, 255, 255 },
	})
table.insert(Effects,
	{
		Type = "sprite",
		TimeToTrigger = 0.12,
		LocalPosition = { x = 300, y = 240, z = 0 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = "missile_explosion",
		Additive = false,
		TimeToLive = 1,
		InitialSize = 4,
		ExpansionRate = 0.5,
		Angle = -90,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 0,
		Colour1 = { 255, 255, 255, 255 },
		Colour2 = { 255, 255, 255, 255 },
	})
table.insert(Effects,
	{
		Type = "sprite",
		TimeToTrigger = 0.18,
		LocalPosition = { x = -300, y = 160, z = 0 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = "missile_explosion",
		Additive = false,
		TimeToLive = 1,
		InitialSize = 4,
		ExpansionRate = 0.5,
		Angle = -90,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 0,
		Colour1 = { 255, 255, 255, 255 },
		Colour2 = { 255, 255, 255, 255 },
	})
table.insert(Effects, Flames(6, 0.6, 2200))
table.insert(Effects, Flames(16, 0.3, 3700))
table.insert(Effects,Dirt(0.3, 2000))
table.insert(Effects,Dirt(0.5, 900))
table.insert(Effects, Smoke(9, 14, 10, 400))
table.insert(Effects, Smoke(18, 8, 6, 600))
table.insert(Effects,
	{
		Type = "sprite",
		TimeToTrigger = 0.2,
		LocalPosition = { x = 0, y = 0, z = -100 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = path .. "/effects/media/bloom3.png",
		Additive = true,
		TimeToLive = 0.4,
		InitialSize = 15,
		ExpansionRate = -700,
		Angle = -90,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 100,
		Colour1 = { 255, 222, 100, 188 },
		Colour2 = { 255, 170, 0, 30 },
	})
table.insert(Effects,
	{
		Type = "sprite",
		TimeToTrigger = 0.24,
		LocalPosition = { x = 120, y = -300, z = -100 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = path .. "/effects/media/bloom1.png",
		Additive = true,
		TimeToLive = 0.32,
		InitialSize = 23,
		ExpansionRate = -900,
		Angle = -90,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 700,
		Colour1 = { 255, 170, 120, 190 },
		Colour2 = { 255, 100, 20, 30 },
	})
table.insert(Effects,
	{
		Type = "sprite",
		TimeToTrigger = 26,
		LocalPosition = { x = -120, y = -200, z = -100 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = path .. "/effects/media/bloom1.png",
		Additive = true,
		TimeToLive = 0.08,
		InitialSize = 6,
		ExpansionRate = -20,
		Angle = 0,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 700,
		Colour1 = { 255, 140, 255, 255 },
		Colour2 = { 255, 140, 255, 128 },
	})
table.insert(Effects,
	{
		Type = "sprite",
		TimeToTrigger = 0.28,
		LocalPosition = { x = 0, y = -200, z = -100 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = path .. "/effects/media/bloom1.png",
		Additive = true,
		TimeToLive = 0.08,
		InitialSize = 6,
		ExpansionRate = -20,
		Angle = 0,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 700,
		Colour1 = { 255, 170, 255, 255 },
		Colour2 = { 255, 170, 255, 255 },
	})
table.insert(Effects,
	{
		Type = "sprite",
		TimeToTrigger = 0.3,
		LocalPosition = { x = 100, y = -180, z = 0 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = "missile_explosion",
		Additive = false,
		TimeToLive = 1,
		InitialSize = 4,
		ExpansionRate = 0.5,
		Angle = -90,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 0,
		Colour1 = { 255, 255, 255, 255 },
		Colour2 = { 255, 255, 255, 255 },
	})
table.insert(Effects,
	{
		Type = "sprite",
		TimeToTrigger = 0.24,
		LocalPosition = { x = 0, y = -280, z = 0 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = "missile_explosion",
		Additive = false,
		TimeToLive = 1,
		InitialSize = 4,
		ExpansionRate = 0.5,
		Angle = -90,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 0,
		Colour1 = { 255, 255, 255, 255 },
		Colour2 = { 255, 255, 255, 255 },
	})
table.insert(Effects,
	{
		Type = "sprite",
		TimeToTrigger = 0.2,
		LocalPosition = { x = -150, y = -200, z = 0 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = "missile_explosion",
		Additive = false,
		TimeToLive = 1,
		InitialSize = 4,
		ExpansionRate = 0.5,
		Angle = -90,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 0,
		Colour1 = { 255, 255, 255, 255 },
		Colour2 = { 255, 255, 255, 255 },
	})
table.insert(Effects, 
	{
		Type = "sprite",
		TimeToTrigger = 0,
		LocalPosition = { x = 0, y = 0, z = -100 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = path .. "/effects/media/bloom1.png",
		Additive = true,
		TimeToLive = 1,
		InitialSize = 55,
		ExpansionRate = -2000,
		Angle = -90,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 0,
		Colour1 = { 255, 150, 100, 150 },
		Colour2 = { 255, 90, 0, 0 },
	}
)
table.insert(Effects, Debris(path .. "/effects/media/debris/ac130_0.png"))
table.insert(Effects, Debris(path .. "/effects/media/debris/ac130_1.png"))
table.insert(Effects, Debris(path .. "/effects/media/debris/ac130_2.png"))
table.insert(Effects, Debris("gunner"))
table.insert(Effects, Debris("gunner"))
table.insert(Effects, Debris("weapons/cannon/barrel_destroyed1.dds"))
table.insert(Effects, Debris("weapons/cannon/barrel_destroyed2.dds"))
table.insert(Effects, Debris("weapons/cannon/head_destroyed.dds"))
table.insert(Effects, Debris("weapons/cannon/base_destroyed.dds"))
table.insert(Effects, DeviceExplodeSprite())
table.insert(Effects, Debris("weapons/gunner.dds"))
table.insert(Effects, Debris("weapons/gunner.dds"))
table.insert(Effects, Debris("mods/weapon_pack/weapons/20mmcannon/barrel_destroyed1.dds"))
table.insert(Effects, Debris("mods/weapon_pack/weapons/20mmcannon/head_destroyed.dds"))
table.insert(Effects, Debris("mods/weapon_pack/weapons/20mmcannon/base_destroyed.dds"))
