LifeSpan = 11111
SCALE = 1.5
Y_OFFSET = 20
Sprites = {}
Effects =
{

	{
		Type = "sprite",
		TimeToTrigger = 0,
		LocalPosition = { x = 0, y = Y_OFFSET, z = 0 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0.0,
		Sprite = path .. "/weapons/ah6/littlebirdL.png",
		Additive = false,
		TimeToLive = 10000,
		Angle = 0,
		InitialSize = SCALE,
		ExpansionRate = 0,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 0,
		Colour1 = { 255, 255, 255, 255 },
		Colour2 = { 255, 255, 255, 255 },
		KillParticleOnEffectCancel = true,
	},
	{
		Type = "sprite",
		TimeToTrigger = 0,
		LocalPosition = { x = -19.875 * SCALE, y = (27.75 * SCALE) + Y_OFFSET, z = 0 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0.0,
		Sprite = "sbpp_ApacheRotorSpin",
		Additive = false,
		TimeToLive = 10000,
		Angle = 0,
		InitialSize = SCALE,
		ExpansionRate = 0,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 0,
		Colour1 = { 255, 255, 255, 255 },
		Colour2 = { 255, 255, 255, 255 },
		KillParticleOnEffectCancel = true,
	},
	{
		Type = "sprite",
		TimeToTrigger = 0,
		LocalPosition = { x = 75 * SCALE, y = (0.75 * SCALE) + Y_OFFSET, z = 0 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0.0,
		Sprite = "sbpp_ApacheTailRotorSpin",
		Additive = false,
		TimeToLive = 10000,
		Angle = 0,
		InitialSize = SCALE,
		ExpansionRate = 0,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 0,
		Colour1 = { 255, 255, 255, 255 },
		Colour2 = { 255, 255, 255, 255 },
		KillParticleOnEffectCancel = true,
	},
}